name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          version: 12.x
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
